[tool.poetry]
name = "DroneRescue"
version = "0.1.0"
description = ""
authors = ["Evgenii Iurin <iurin.evgenii@gmail.com>"]
readme = "README.md"
packages = [{ include = "src" }]
package-mode = true

[tool.poetry.dependencies]
python = "^3.10"
langchain-openai = "^0.2.9"
pillow = "^11.0.0"
pre-commit = "^4.0.1"
hydra-core = "^1.3.2"
python-dotenv = "^1.0.1"
langgraph = "^0.2.61"
langchain = "^0.3.14"
langchain-community = "^0.3.14"
streamlit = "^1.44.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
