path_to_hydra_outputs: "/home/evgenii-iurin/work/DroneRescue/v2_1/hydra_outputs"
author: "Eugene Iurin"
base_path: ./v2_1
agents:
  scout:
    role: "scout"
    number:
      min: 1
      max: 2
    symbol: "o"
    color: "blue"
    mission: "Find the position of targets and send coordinates to rescuer"
    global_strategy: "scout targets"
    position_range:
      min_yx: [1, 1]
      max_yx: ${metadata.size_of_mission_area}
    sensor:
      range: 35 # diameter
    special_action:
      name: "Scan all targets"
      id: 1
    shape: 1F79B
    size: 20

  rescuer:
    role: "rescuer"
    number:
      min: 1
      max: 1
    symbol: "*"
    color: "green"
    mission: "Based on the coordinates provided by scout, scan all targets"
    global_strategy: "Scan all targets"
    position_range:
      min_yx: [1, 1]
      max_yx: ${metadata.size_of_mission_area}
    sensor:
      range: 20
    special_action:
      name: "scan area"
      id: 2
    shape: 25C9
    size: 20


  scout_commander:
    role: "scout_commander"
    number:
      min: 1
      max: 1
    symbol: "D"
    color: "purple"
    mission: "Coordinaate scouts and rescuers to find and scan targets"
    global_strategy: "Scan all targets"
    position_range:
      min_yx: [1, 1]
      max_yx: ${metadata.size_of_mission_area}
    sensor:
      range: 50
    special_action:
      name: "send order"
      id: 3
    shape: 1F7CA
    size: 20

targets:
  symbol: "x"
  color: "red"
  number:
    min: 1
    max: 3
  position_range:
    min_yx: [1, 1]
    max_yx: ${metadata.size_of_mission_area}
  sampled_targets: {}
  shape: 1F7AD
  size: 20

base:
  symbol: "p"
  color: "orange"
  possible_position_ranges:
    - [[5, 5], [5, 95]] # y, x
    - [[5, 5], [95, 5]] # y, x
    - [[95, 5], [95, 95]] # y, x
    - [[5, 95], [95, 95]] # y, x
  shape: 1F78E
  size: 20
  sampled_bases: {}


metadata:
  size_of_mission_area: [100, 100]
  scale_factor: 4
  save_datasample_to: ${base_path}/datasamples
